name: Setup Repository
description: Install `pnpm`, configure `Node.js` with caching, and install dependencies.

inputs:
  node-version-file:
    description: Path to file specifying Node.js version (default '.nvmrc')
    required: false
    default: ".nvmrc"
  pnpm-version:
    description: pnpm version (matches pnpm-lock.yaml format)
    required: false
    default: "8.6.1"

runs:
  using: composite
  steps:
    - name: Enable `pnpm` via `corepack`
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup `Node.js` with `pnpm` store cache
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
